"""First-run onboarding TUI for Sarus.

Presets the Microsoft public-client settings, asks the user for their Anthropic
API key, and writes a local .env. Built with Textual (a TUI framework) — note
this is the one deliberate exception to the project's "four deps only" rule;
see CLAUDE.md.

Run standalone:  python setup.py
"""

import os
import shutil
import subprocess
import sys
from pathlib import Path
from xml.sax.saxutils import escape

from textual.app import App, ComposeResult
from textual.containers import Vertical, VerticalScroll
from textual.widgets import Button, Input, Label, Static

# launchd job labels (also the plist filenames in ~/Library/LaunchAgents).
DIGEST_LABEL = "com.sarus.briefing"  # daily mail digest
PREP_LABEL = "com.sarus.prep"        # 30-min meeting-prep poll

# Minutes-past-the-hour at which the meeting-prep poll fires (every hour).
# Fixed clock times beat a drifting StartInterval: predictable, easy to read in
# the log, and the :05/:35 offset gives a ~25-min lead for the common :00/:30
# meeting starts. 30-min spacing < PREP_WINDOW_MINUTES (35) so nothing is missed.
PREP_POLL_MINUTES = (5, 35)

# Preset Microsoft public-client settings. The client ID is NOT a secret — it is
# Microsoft's first-party "Graph Command Line Tools" public client, which supports
# personal accounts + device-code flow. Authority /consumers = personal accounts.
MS_CLIENT_ID = "14d82eec-204b-4c2f-b7e8-296a70dab67e"
MS_TENANT_AUTHORITY = "https://login.microsoftonline.com/consumers"

# Default triage model written into .env (swappable there without code changes).
DEFAULT_MODEL = "claude-sonnet-4-6"

# "SARUS" ASCII banner. RAW string (r"""…) so the backslashes are literal art,
# not escape sequences — otherwise a line-ending "\" merges rows and Python warns.
CRANE_ART = r""" ____   __   ____  _  _  ____
/ ___) / _\ (  _ \/ )( \/ ___)
\___ \/    \ )   /) \/ (\___ \
(____/\_/\_/(__\_)\____/(____/
"""


def build_env(anthropic_key: str) -> str:
    """Return the full text of a .env file for the given Anthropic API key."""
    return (
        "# Sarus configuration — generated by setup.py. Gitignored; never commit.\n\n"
        "# LLM provider. Only 'anthropic' is implemented today.\n"
        "PROVIDER=anthropic\n\n"
        "# Anthropic API key (the anthropic SDK reads this from the environment).\n"
        f"ANTHROPIC_API_KEY={anthropic_key}\n\n"
        "# Triage + prep model. Default claude-sonnet-4-6; use claude-haiku-4-5 for cheaper/faster.\n"
        f"MODEL={DEFAULT_MODEL}\n\n"
        "# Microsoft Graph public client (not a secret). Preset for personal accounts.\n"
        "# Work/school account? Replace /consumers below with your tenant id, e.g.\n"
        "# MS_TENANT_AUTHORITY=https://login.microsoftonline.com/<tenant-id>\n"
        f"MS_CLIENT_ID={MS_CLIENT_ID}\n"
        f"MS_TENANT_AUTHORITY={MS_TENANT_AUTHORITY}\n"
    )


def write_env(anthropic_key: str, path: str = ".env") -> Path:
    """Write the .env file and return its path."""
    target = Path(path)
    target.write_text(build_env(anthropic_key))
    return target


# --- Scheduling (portable: every path is derived at runtime, nothing hardcoded) ---

def _project_dir() -> Path:
    """The directory this repo lives in (where sarus.py / .env / briefings/ are)."""
    return Path(__file__).resolve().parent


def _venv_python() -> str:
    """Path to the venv's Python if present, else whatever Python is running setup."""
    venv_py = _project_dir() / "venv" / "bin" / "python"
    return str(venv_py if venv_py.exists() else Path(sys.executable))


def _homebrew_bin() -> str | None:
    """Best-effort Homebrew bin dir so the LaunchAgent can find `alerter`.

    Works on both Apple Silicon (/opt/homebrew) and Intel (/usr/local) by asking
    `brew --prefix` first, then falling back to the known locations.
    """
    brew = shutil.which("brew")
    if brew:
        try:
            out = subprocess.run([brew, "--prefix"], capture_output=True,
                                 text=True, timeout=10).stdout.strip()
            if out:
                return str(Path(out) / "bin")
        except (FileNotFoundError, subprocess.SubprocessError):
            pass
    for cand in ("/opt/homebrew/bin", "/usr/local/bin"):
        if Path(cand).is_dir():
            return cand
    return None


def _build_plist(label: str, script: str, schedule_xml: str) -> str:
    """Render a launchd LaunchAgent plist running `script` on `schedule_xml`.

    All paths are derived at runtime (nothing hardcoded). `schedule_xml` is the
    inner key/value block selecting when to run (StartCalendarInterval for the
    daily digest, StartInterval for the prep poll).
    """
    proj = str(_project_dir())
    python = _venv_python()
    log = str(_project_dir() / "sarus.log")
    brew_bin = _homebrew_bin()
    path_value = ":".join(d for d in (brew_bin, "/usr/bin", "/bin", "/usr/sbin", "/sbin") if d)
    return f"""<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>{label}</string>
    <key>ProgramArguments</key>
    <array>
        <string>{escape(python)}</string>
        <string>{escape(proj + "/" + script)}</string>
    </array>
    <key>WorkingDirectory</key>
    <string>{escape(proj)}</string>
    <key>EnvironmentVariables</key>
    <dict>
        <key>PATH</key>
        <string>{escape(path_value)}</string>
    </dict>
{schedule_xml}
    <key>StandardOutPath</key>
    <string>{escape(log)}</string>
    <key>StandardErrorPath</key>
    <string>{escape(log)}</string>
    <key>RunAtLoad</key>
    <false/>
</dict>
</plist>
"""


def build_digest_plist(hour: int, minute: int) -> str:
    """LaunchAgent plist for the daily mail digest at HH:MM."""
    schedule = (f"    <key>StartCalendarInterval</key>\n"
                f"    <dict>\n"
                f"        <key>Hour</key>\n        <integer>{hour}</integer>\n"
                f"        <key>Minute</key>\n        <integer>{minute}</integer>\n"
                f"    </dict>")
    return _build_plist(DIGEST_LABEL, "sarus.py", schedule)


def build_prep_plist() -> str:
    """LaunchAgent plist for the meeting-prep poll at PREP_POLL_MINUTES past each hour."""
    entries = "\n".join(
        f"        <dict>\n"
        f"            <key>Minute</key>\n            <integer>{m}</integer>\n"
        f"        </dict>"
        for m in PREP_POLL_MINUTES
    )
    schedule = (f"    <key>StartCalendarInterval</key>\n"
                f"    <array>\n{entries}\n    </array>")
    return _build_plist(PREP_LABEL, "prep.py", schedule)


def _launchagents_plist(label: str) -> Path:
    return Path.home() / "Library" / "LaunchAgents" / f"{label}.plist"


def install_agent(label: str, plist_text: str) -> Path:
    """Write a LaunchAgent plist and (re)load it into the user's GUI session.

    Returns the plist path. Raises CalledProcessError if launchctl bootstrap fails.
    """
    target = _launchagents_plist(label)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(plist_text)
    uid = os.getuid()
    # bootout first so re-running setup cleanly replaces an existing schedule.
    subprocess.run(["launchctl", "bootout", f"gui/{uid}/{label}"], capture_output=True)
    subprocess.run(["launchctl", "bootstrap", f"gui/{uid}", str(target)],
                   check=True, capture_output=True, text=True)
    return target


def uninstall_agent(label: str) -> None:
    """Unload a LaunchAgent and remove its plist (used when prep is disabled)."""
    uid = os.getuid()
    subprocess.run(["launchctl", "bootout", f"gui/{uid}/{label}"], capture_output=True)
    _launchagents_plist(label).unlink(missing_ok=True)


def install_digest_schedule(hour: int, minute: int) -> Path:
    return install_agent(DIGEST_LABEL, build_digest_plist(hour, minute))


def install_prep_schedule() -> Path:
    return install_agent(PREP_LABEL, build_prep_plist())


def cron_line_digest(hour: int, minute: int) -> str:
    """Crontab line for the daily digest, for non-macOS / headless self-hosters."""
    brew_bin = _homebrew_bin() or "/usr/local/bin"
    return (f"{minute} {hour} * * * cd {_project_dir()} && "
            f"PATH={brew_bin}:$PATH {_venv_python()} sarus.py >> sarus.log 2>&1")


def cron_line_prep() -> str:
    """Crontab line for the meeting-prep poll at PREP_POLL_MINUTES past each hour."""
    brew_bin = _homebrew_bin() or "/usr/local/bin"
    minutes = ",".join(str(m) for m in PREP_POLL_MINUTES)
    return (f"{minutes} * * * * cd {_project_dir()} && "
            f"PATH={brew_bin}:$PATH {_venv_python()} prep.py >> sarus.log 2>&1")


def _warn_if_no_alerter() -> None:
    """Notifications rely on `alerter`; warn (don't fail) if it's missing."""
    if sys.platform == "darwin" and not shutil.which("alerter"):
        print("\n[!] `alerter` not found — briefing banners won't appear.")
        print("    Install it for clickable notifications:  brew install alerter")
        print("    (The HTML briefing is still written to briefings/ either way.)")


def _ask_digest_time() -> tuple[int, int] | None:
    """Prompt for the daily digest time. Returns (hour, minute), or None to skip."""
    ans = input("Daily digest time as HH:MM (Enter = 07:00, 'n' = skip): ").strip()
    if ans.lower() in ("n", "no", "skip"):
        return None
    if not ans:
        return 7, 0
    try:
        hh, mm = ans.split(":")
        hour, minute = int(hh), int(mm)
        if not (0 <= hour < 24 and 0 <= minute < 60):
            raise ValueError
        return hour, minute
    except ValueError:
        print(f"Couldn't read '{ans}' as HH:MM — using 07:00.")
        return 7, 0


def configure_schedule_interactive() -> None:
    """Plain-terminal onboarding: install the digest + (optional) prep schedules.

    macOS installs LaunchAgents (they run in the GUI session, so the alerter
    notifications fire); elsewhere we print the equivalent cron lines. Kept out
    of the Textual TUI so the scheduling logic stays framework-free and reusable.
    """
    _warn_if_no_alerter()

    print("\n— Mailbox —")
    print("Default account type is personal (/consumers). For a work/school account,")
    print("set MS_TENANT_AUTHORITY in .env to https://login.microsoftonline.com/<tenant-id>.")

    digest_time = _ask_digest_time()
    prep_ans = input("\nEnable meeting prep? Polls every 30 min for upcoming meetings (y/N): ").strip().lower()
    prep_enabled = prep_ans in ("y", "yes")

    if sys.platform != "darwin":
        print("\n— Schedule (non-macOS) — add these to `crontab -e`:")
        if digest_time:
            print("  " + cron_line_digest(*digest_time))
        if prep_enabled:
            print("  " + cron_line_prep())
        print("  Note: cron runs outside the GUI session, so notification banners may not appear.")
        return

    uid = os.getuid()
    print("\n— Schedule (macOS LaunchAgents) —")

    if digest_time:
        try:
            target = install_digest_schedule(*digest_time)
            print(f"✓ Daily digest at {digest_time[0]:02d}:{digest_time[1]:02d}  ({target})")
            print(f"  Test now:  launchctl kickstart gui/{uid}/{DIGEST_LABEL}")
        except subprocess.CalledProcessError as e:
            print(f"[!] launchctl failed for the digest: {(e.stderr or '').strip() or e}")
            print("    Cron alternative:  " + cron_line_digest(*digest_time))
    else:
        print("Digest schedule skipped.")

    if prep_enabled:
        try:
            target = install_prep_schedule()
            print(f"✓ Meeting prep every 30 min  ({target})")
            print(f"  Test now:  launchctl kickstart gui/{uid}/{PREP_LABEL}")
        except subprocess.CalledProcessError as e:
            print(f"[!] launchctl failed for prep: {(e.stderr or '').strip() or e}")
            print("    Cron alternative:  " + cron_line_prep())
    else:
        uninstall_agent(PREP_LABEL)  # ensure any prior prep agent is removed
        print("Meeting prep disabled.")

    print(f"\n  Disable digest:  launchctl bootout gui/{uid}/{DIGEST_LABEL}")
    print(f"  Disable prep:    launchctl bootout gui/{uid}/{PREP_LABEL}")
    print("  Tip: run `python sarus.py` once first to sign in, so scheduled runs auth silently.")


class SarusSetup(App):
    """Onboarding screen: collect the Anthropic key, write .env."""

    CSS = """
    VerticalScroll {
        align-horizontal: center;
    }
    #card {
        width: 70;
        height: auto;
        margin: 1 0;
        border: round $accent;
        padding: 1 2;
        background: $surface;
    }
    #crane {
        color: $accent;
        content-align: center middle;
        height: auto;
        margin-bottom: 1;
    }
    #title {
        text-style: bold;
        content-align: center middle;
        color: $accent;
    }
    #subtitle {
        content-align: center middle;
        color: $text-muted;
        margin-bottom: 1;
    }
    .preset {
        color: $text-muted;
    }
    #status {
        margin-top: 1;
        height: auto;
    }
    #save {
        margin-top: 1;
        width: 100%;
    }
    """

    BINDINGS = [("ctrl+c", "quit", "Quit")]

    def __init__(self, env_path: str = ".env") -> None:
        super().__init__()
        self.env_path = env_path
        self.written_path: Path | None = None

    def compose(self) -> ComposeResult:
        # VerticalScroll keeps the Save button reachable even on short terminals.
        with VerticalScroll():
            with Vertical(id="card"):
                yield Static(CRANE_ART, id="crane")
                yield Static("S A R U S", id="title")
                yield Static("read-only email triage · first-run setup", id="subtitle")
                yield Label(f"Microsoft client ID  ·  {MS_CLIENT_ID}  (preset ✓)", classes="preset")
                yield Label(f"Tenant authority     ·  /consumers  (preset ✓)", classes="preset")
                yield Label("\nPaste your Anthropic API key, then press Enter:")
                yield Input(
                    placeholder="sk-ant-...",
                    password=True,
                    id="key",
                )
                yield Static("", id="status")
                yield Button("Save & Continue", variant="primary", id="save")

    def on_input_submitted(self, event: Input.Submitted) -> None:
        self._save()

    def on_button_pressed(self, event: Button.Pressed) -> None:
        if event.button.id == "save":
            self._save()

    def _save(self) -> None:
        key = self.query_one("#key", Input).value.strip()
        status = self.query_one("#status", Static)
        if not key:
            status.update("[red]Please paste your Anthropic API key.[/red]")
            return
        if not key.startswith("sk-"):
            status.update("[red]That doesn't look like an Anthropic key (expected sk-...).[/red]")
            return
        self.written_path = write_env(key, self.env_path)
        status.update(f"[green]✓ Wrote {self.written_path}[/green]")
        # Exit the TUI cleanly; the launcher continues with login in plain terminal.
        self.set_timer(0.6, self.exit)


def run_setup(env_path: str = ".env") -> Path | None:
    """Launch the onboarding TUI. Returns the written .env path, or None if cancelled."""
    app = SarusSetup(env_path=env_path)
    app.run()
    return app.written_path


if __name__ == "__main__":
    written = run_setup()
    if written:
        print(f"\nSetup complete — wrote {written}.")
        print("Next: run  python sarus.py  to sign in to Microsoft and get your first briefing.")
        configure_schedule_interactive()
    else:
        print("\nSetup cancelled — no .env written.")
